workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: 3.10.6
      java: 11
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build AAB
        script: flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/*.apk
